name: myenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.13.9=h260b955_100_cp313
  - python_abi=3.13=1_cp313
  - setuptools=80.9.0=py313haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==1.0.2
      - langchain-core==1.0.1
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.38
      - orjson==3.11.4
      - ormsgpack==1.11.0
      - packaging==25.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: C:\Users\VIJAY\.conda\envs\myenv
